// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// 
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDow28VMaOkjsx_exYbpeKUBsPm84Kb5D0',
    appId: '1:195872803608:web:2fc51064c1a16abd546c6d',
    messagingSenderId: '195872803608',
    projectId: 'planify-firebase-72706',
    authDomain: 'planify-firebase-72706.firebaseapp.com',
    storageBucket: 'planify-firebase-72706.appspot.com',
    measurementId: 'G-KJH10J8C24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY65Et69BmpXUhRBofvB5ETMwo2TkQZe0',
    appId: '1:195872803608:android:229a9bcc282789df546c6d',
    messagingSenderId: '195872803608',
    projectId: 'planify-firebase-72706',
    storageBucket: 'planify-firebase-72706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwdi9Jox47qH5Vn9P2Q140PlCd5iul-bE',
    appId: '1:195872803608:ios:1b89bad397cf4c57546c6d',
    messagingSenderId: '195872803608',
    projectId: 'planify-firebase-72706',
    storageBucket: 'planify-firebase-72706.appspot.com',
    iosBundleId: 'com.example.planify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwdi9Jox47qH5Vn9P2Q140PlCd5iul-bE',
    appId: '1:195872803608:ios:1b89bad397cf4c57546c6d',
    messagingSenderId: '195872803608',
    projectId: 'planify-firebase-72706',
    storageBucket: 'planify-firebase-72706.appspot.com',
    iosBundleId: 'com.example.planify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDow28VMaOkjsx_exYbpeKUBsPm84Kb5D0',
    appId: '1:195872803608:web:dbe25847b2532231546c6d',
    messagingSenderId: '195872803608',
    projectId: 'planify-firebase-72706',
    authDomain: 'planify-firebase-72706.firebaseapp.com',
    storageBucket: 'planify-firebase-72706.appspot.com',
    measurementId: 'G-ZV22TT08EJ',
  );

}